using System;
using System.Collections.Generic;
using System.Text;

namespace BL.OfflineCompaniesData.Models.RoicAi_Old
{
    public class BalanceSheet_Old
    {
        public BalanceSheetData data { get; set; }
        public List<BalanceSheetView> view { get; set; }
        public string name { get; set; }
    }
    public class BalanceSheetData
    {
        public List<string> bsCAndCeAndStiDetailed_annual { get; set; }
        public List<string> bsCAndCeAndStiDetailed_ttm { get; set; }
        public List<string> bsCAndCeAndStiDetailed_quarterly { get; set; }
        public List<string> bsCashNearCashItem_annual { get; set; }
        public List<string> bsCashNearCashItem_ttm { get; set; }
        public List<string> bsCashNearCashItem_quarterly { get; set; }
        public List<string> bsMktSecOtherStInvest_annual { get; set; }
        public List<string> bsMktSecOtherStInvest_ttm { get; set; }
        public List<string> bsMktSecOtherStInvest_quarterly { get; set; }
        public List<string> bsTotAsset_annual { get; set; }
        public List<string> bsTotAsset_ttm { get; set; }
        public List<string> bsTotAsset_quarterly { get; set; }
        public List<string> bsAcctNoteRcv_annual { get; set; }
        public List<string> bsAcctNoteRcv_ttm { get; set; }
        public List<string> bsAcctNoteRcv_quarterly { get; set; }
        public List<string> bsAcctsRecExclNotesRec_annual { get; set; }
        public List<string> bsAcctsRecExclNotesRec_ttm { get; set; }
        public List<string> bsAcctsRecExclNotesRec_quarterly { get; set; }
        public List<string> bsNotesReceivable_annual { get; set; }
        public List<string> bsNotesReceivable_ttm { get; set; }
        public List<string> bsNotesReceivable_quarterly { get; set; }
        public List<string> bsLoansReceivable_annual { get; set; }
        public List<string> bsLoansReceivable_ttm { get; set; }
        public List<string> bsLoansReceivable_quarterly { get; set; }
        public List<string> bsOtherCurrentReceivable_annual { get; set; }
        public List<string> bsOtherCurrentReceivable_ttm { get; set; }
        public List<string> bsOtherCurrentReceivable_quarterly { get; set; }
        public List<string> bsInventories_annual { get; set; }
        public List<string> bsInventories_ttm { get; set; }
        public List<string> bsInventories_quarterly { get; set; }
        public List<string> bsInvtryRawMaterials_annual { get; set; }
        public List<string> bsInvtryRawMaterials_ttm { get; set; }
        public List<string> bsInvtryRawMaterials_quarterly { get; set; }
        public List<string> bsInvtryInProgress_annual { get; set; }
        public List<string> bsInvtryInProgress_ttm { get; set; }
        public List<string> bsInvtryInProgress_quarterly { get; set; }
        public List<string> bsInvtryFinishedGoods_annual { get; set; }
        public List<string> bsInvtryFinishedGoods_ttm { get; set; }
        public List<string> bsInvtryFinishedGoods_quarterly { get; set; }
        public List<string> bsInvtryAdj_annual { get; set; }
        public List<string> bsInvtryAdj_ttm { get; set; }
        public List<string> bsInvtryAdj_quarterly { get; set; }
        public List<string> bsOtherInv_annual { get; set; }
        public List<string> bsOtherInv_ttm { get; set; }
        public List<string> bsOtherInv_quarterly { get; set; }
        public List<string> bsOtherCurrentAssetsDetailed_annual { get; set; }
        public List<string> bsOtherCurrentAssetsDetailed_ttm { get; set; }
        public List<string> bsOtherCurrentAssetsDetailed_quarterly { get; set; }
        public List<string> bsPrepay_annual { get; set; }
        public List<string> bsPrepay_ttm { get; set; }
        public List<string> bsPrepay_quarterly { get; set; }
        public List<string> bsDerivAndHedgingAssetsSt_annual { get; set; }
        public List<string> bsDerivAndHedgingAssetsSt_ttm { get; set; }
        public List<string> bsDerivAndHedgingAssetsSt_quarterly { get; set; }
        public List<string> bsAssetsHeldForSaleSt_annual { get; set; }
        public List<string> bsAssetsHeldForSaleSt_ttm { get; set; }
        public List<string> bsAssetsHeldForSaleSt_quarterly { get; set; }
        public List<string> bsDeferredTaxAssetsSt_annual { get; set; }
        public List<string> bsDeferredTaxAssetsSt_ttm { get; set; }
        public List<string> bsDeferredTaxAssetsSt_quarterly { get; set; }
        public List<string> bsOtherCurAssetLessPrepay_annual { get; set; }
        public List<string> bsOtherCurAssetLessPrepay_ttm { get; set; }
        public List<string> bsOtherCurAssetLessPrepay_quarterly { get; set; }
        public List<string> bsCurAssetReport_annual { get; set; }
        public List<string> bsCurAssetReport_ttm { get; set; }
        public List<string> bsCurAssetReport_quarterly { get; set; }
        public List<string> bsNetFixAsset_annual { get; set; }
        public List<string> bsNetFixAsset_ttm { get; set; }
        public List<string> bsNetFixAsset_quarterly { get; set; }
        public List<string> bsGrossFixAsset_annual { get; set; }
        public List<string> bsGrossFixAsset_ttm { get; set; }
        public List<string> bsGrossFixAsset_quarterly { get; set; }
        public List<string> bsAccumDepr_annual { get; set; }
        public List<string> bsAccumDepr_ttm { get; set; }
        public List<string> bsAccumDepr_quarterly { get; set; }
        public List<string> bsLtInvest_annual { get; set; }
        public List<string> bsLtInvest_ttm { get; set; }
        public List<string> bsLtInvest_quarterly { get; set; }
        public List<string> bsLongTermInvestments_annual { get; set; }
        public List<string> bsLongTermInvestments_ttm { get; set; }
        public List<string> bsLongTermInvestments_quarterly { get; set; }
        public List<string> bsLtReceivables_annual { get; set; }
        public List<string> bsLtReceivables_ttm { get; set; }
        public List<string> bsLtReceivables_quarterly { get; set; }
        public List<string> bsOtherAssetsDefChrgOther_annual { get; set; }
        public List<string> bsOtherAssetsDefChrgOther_ttm { get; set; }
        public List<string> bsOtherAssetsDefChrgOther_quarterly { get; set; }
        public List<string> bsDisclosedIntangibles_annual { get; set; }
        public List<string> bsDisclosedIntangibles_ttm { get; set; }
        public List<string> bsDisclosedIntangibles_quarterly { get; set; }
        public List<string> bsGoodwill_annual { get; set; }
        public List<string> bsGoodwill_ttm { get; set; }
        public List<string> bsGoodwill_quarterly { get; set; }
        public List<string> bsOtherIntangibleAssetsDetailed_annual { get; set; }
        public List<string> bsOtherIntangibleAssetsDetailed_ttm { get; set; }
        public List<string> bsOtherIntangibleAssetsDetailed_quarterly { get; set; }
        public List<string> bsDeferredTaxAssetsLt_annual { get; set; }
        public List<string> bsDeferredTaxAssetsLt_ttm { get; set; }
        public List<string> bsDeferredTaxAssetsLt_quarterly { get; set; }
        public List<string> bsDerivAndHedgingAssetsLt_annual { get; set; }
        public List<string> bsDerivAndHedgingAssetsLt_ttm { get; set; }
        public List<string> bsDerivAndHedgingAssetsLt_quarterly { get; set; }
        public List<string> bsOtherNoncurrentAssetsDetailed_annual { get; set; }
        public List<string> bsOtherNoncurrentAssetsDetailed_ttm { get; set; }
        public List<string> bsOtherNoncurrentAssetsDetailed_quarterly { get; set; }
        public List<string> bsTotNonCurAsset_annual { get; set; }
        public List<string> bsTotNonCurAsset_ttm { get; set; }
        public List<string> bsTotNonCurAsset_quarterly { get; set; }
        public List<string> bsAcctPayableAndAccrualsDetailed_annual { get; set; }
        public List<string> bsAcctPayableAndAccrualsDetailed_ttm { get; set; }
        public List<string> bsAcctPayableAndAccrualsDetailed_quarterly { get; set; }
        public List<string> bsAcctPayable_annual { get; set; }
        public List<string> bsAcctPayable_ttm { get; set; }
        public List<string> bsAcctPayable_quarterly { get; set; }
        public List<string> bsTaxesPayable_annual { get; set; }
        public List<string> bsTaxesPayable_ttm { get; set; }
        public List<string> bsTaxesPayable_quarterly { get; set; }
        public List<string> bsInterestAndDividendsPayable_annual { get; set; }
        public List<string> bsInterestAndDividendsPayable_ttm { get; set; }
        public List<string> bsInterestAndDividendsPayable_quarterly { get; set; }
        public List<string> bsAccrual_annual { get; set; }
        public List<string> bsAccrual_ttm { get; set; }
        public List<string> bsAccrual_quarterly { get; set; }
        public List<string> bsStBorrow_annual { get; set; }
        public List<string> bsStBorrow_ttm { get; set; }
        public List<string> bsStBorrow_quarterly { get; set; }
        public List<string> bsShortTermDebtDetailed_annual { get; set; }
        public List<string> bsShortTermDebtDetailed_ttm { get; set; }
        public List<string> bsShortTermDebtDetailed_quarterly { get; set; }
        public List<string> bsStCapitalLeaseObligations_annual { get; set; }
        public List<string> bsStCapitalLeaseObligations_ttm { get; set; }
        public List<string> bsStCapitalLeaseObligations_quarterly { get; set; }
        public List<string> bsOtherCurrentLiabsSubDetailed_annual { get; set; }
        public List<string> bsOtherCurrentLiabsSubDetailed_ttm { get; set; }
        public List<string> bsOtherCurrentLiabsSubDetailed_quarterly { get; set; }
        public List<string> bsStDeferredRevenue_annual { get; set; }
        public List<string> bsStDeferredRevenue_ttm { get; set; }
        public List<string> bsStDeferredRevenue_quarterly { get; set; }
        public List<string> bsDerivativeAndHedgingLiabsSt_annual { get; set; }
        public List<string> bsDerivativeAndHedgingLiabsSt_ttm { get; set; }
        public List<string> bsDerivativeAndHedgingLiabsSt_quarterly { get; set; }
        public List<string> bsDeferredTaxLiabsSt_annual { get; set; }
        public List<string> bsDeferredTaxLiabsSt_ttm { get; set; }
        public List<string> bsDeferredTaxLiabsSt_quarterly { get; set; }
        public List<string> bsOtherCurrentLiabsDetailed_annual { get; set; }
        public List<string> bsOtherCurrentLiabsDetailed_ttm { get; set; }
        public List<string> bsOtherCurrentLiabsDetailed_quarterly { get; set; }
        public List<string> bsCurLiab_annual { get; set; }
        public List<string> bsCurLiab_ttm { get; set; }
        public List<string> bsCurLiab_quarterly { get; set; }
        public List<string> bsLtBorrow_annual { get; set; }
        public List<string> bsLtBorrow_ttm { get; set; }
        public List<string> bsLtBorrow_quarterly { get; set; }
        public List<string> bsLongTermBorrowingsDetailed_annual { get; set; }
        public List<string> bsLongTermBorrowingsDetailed_ttm { get; set; }
        public List<string> bsLongTermBorrowingsDetailed_quarterly { get; set; }
        public List<string> bsLtCapitalLeaseObligations_annual { get; set; }
        public List<string> bsLtCapitalLeaseObligations_ttm { get; set; }
        public List<string> bsLtCapitalLeaseObligations_quarterly { get; set; }
        public List<string> bsOtherNoncurLiabsSubDetailed_annual { get; set; }
        public List<string> bsOtherNoncurLiabsSubDetailed_ttm { get; set; }
        public List<string> bsOtherNoncurLiabsSubDetailed_quarterly { get; set; }
        public List<string> bsAccruedLiabilities_annual { get; set; }
        public List<string> bsAccruedLiabilities_ttm { get; set; }
        public List<string> bsAccruedLiabilities_quarterly { get; set; }
        public List<string> bsPensionLiabilities_annual { get; set; }
        public List<string> bsPensionLiabilities_ttm { get; set; }
        public List<string> bsPensionLiabilities_quarterly { get; set; }
        public List<string> bsLtDeferredRevenue_annual { get; set; }
        public List<string> bsLtDeferredRevenue_ttm { get; set; }
        public List<string> bsLtDeferredRevenue_quarterly { get; set; }
        public List<string> bsDeferredTaxLiabilitiesLt_annual { get; set; }
        public List<string> bsDeferredTaxLiabilitiesLt_ttm { get; set; }
        public List<string> bsDeferredTaxLiabilitiesLt_quarterly { get; set; }
        public List<string> bsDerivativeAndHedgingLiabsLt_annual { get; set; }
        public List<string> bsDerivativeAndHedgingLiabsLt_ttm { get; set; }
        public List<string> bsDerivativeAndHedgingLiabsLt_quarterly { get; set; }
        public List<string> bsOtherNoncurrentLiabsDetailed_annual { get; set; }
        public List<string> bsOtherNoncurrentLiabsDetailed_ttm { get; set; }
        public List<string> bsOtherNoncurrentLiabsDetailed_quarterly { get; set; }
        public List<string> bsNonCurLiab_annual { get; set; }
        public List<string> bsNonCurLiab_ttm { get; set; }
        public List<string> bsNonCurLiab_quarterly { get; set; }
        public List<string> bsTotLiab_annual { get; set; }
        public List<string> bsTotLiab_ttm { get; set; }
        public List<string> bsTotLiab_quarterly { get; set; }
        public List<string> bsPfdEqtyAndHybridCptl_annual { get; set; }
        public List<string> bsPfdEqtyAndHybridCptl_ttm { get; set; }
        public List<string> bsPfdEqtyAndHybridCptl_quarterly { get; set; }
        public List<string> bsShCapAndApic_annual { get; set; }
        public List<string> bsShCapAndApic_ttm { get; set; }
        public List<string> bsShCapAndApic_quarterly { get; set; }
        public List<string> bsCommonStock_annual { get; set; }
        public List<string> bsCommonStock_ttm { get; set; }
        public List<string> bsCommonStock_quarterly { get; set; }
        public List<string> bsAddPaidInCap_annual { get; set; }
        public List<string> bsAddPaidInCap_ttm { get; set; }
        public List<string> bsAddPaidInCap_quarterly { get; set; }
        public List<string> bsAmtOfTsyStock_annual { get; set; }
        public List<string> bsAmtOfTsyStock_ttm { get; set; }
        public List<string> bsAmtOfTsyStock_quarterly { get; set; }
        public List<string> bsPureRetainedEarnings_annual { get; set; }
        public List<string> bsPureRetainedEarnings_ttm { get; set; }
        public List<string> bsPureRetainedEarnings_quarterly { get; set; }
        public List<string> bsOtherInsResToShrhldrEqy_annual { get; set; }
        public List<string> bsOtherInsResToShrhldrEqy_ttm { get; set; }
        public List<string> bsOtherInsResToShrhldrEqy_quarterly { get; set; }
        public List<string> bsEqtyBefMinorityIntDetailed_annual { get; set; }
        public List<string> bsEqtyBefMinorityIntDetailed_ttm { get; set; }
        public List<string> bsEqtyBefMinorityIntDetailed_quarterly { get; set; }
        public List<string> bsMinorityNoncontrollingInterest_annual { get; set; }
        public List<string> bsMinorityNoncontrollingInterest_ttm { get; set; }
        public List<string> bsMinorityNoncontrollingInterest_quarterly { get; set; }
        public List<string> bsTotalEquity_annual { get; set; }
        public List<string> bsTotalEquity_ttm { get; set; }
        public List<string> bsTotalEquity_quarterly { get; set; }
        public List<string> bsTotLiabAndEqy_annual { get; set; }
        public List<string> bsTotLiabAndEqy_ttm { get; set; }
        public List<string> bsTotLiabAndEqy_quarterly { get; set; }
        public List<string> bsShOut_annual { get; set; }
        public List<string> bsShOut_ttm { get; set; }
        public List<string> bsShOut_quarterly { get; set; }
        public List<string> bsTotalCapitalLeases_annual { get; set; }
        public List<string> bsTotalCapitalLeases_ttm { get; set; }
        public List<string> bsTotalCapitalLeases_quarterly { get; set; }
        public List<string> netDebt_annual { get; set; }
        public List<string> netDebt_ttm { get; set; }
        public List<string> netDebt_quarterly { get; set; }
        public List<string> netDebtToShrhldrEqty_annual { get; set; }
        public List<string> netDebtToShrhldrEqty_ttm { get; set; }
        public List<string> netDebtToShrhldrEqty_quarterly { get; set; }
        public List<string> tceRatio_annual { get; set; }
        public List<string> tceRatio_ttm { get; set; }
        public List<string> tceRatio_quarterly { get; set; }
        public List<string> curRatio_annual { get; set; }
        public List<string> curRatio_ttm { get; set; }
        public List<string> curRatio_quarterly { get; set; }
        public List<string> cashConversionCycle_annual { get; set; }
        public List<string> cashConversionCycle_ttm { get; set; }
        public List<string> cashConversionCycle_quarterly { get; set; }
        public List<string> numOfEmployees_annual { get; set; }
        public List<string> numOfEmployees_ttm { get; set; }
        public List<string> numOfEmployees_quarterly { get; set; }
        public List<string> fiscal_period_annual { get; set; }
        public List<string> fiscal_period_ttm { get; set; }
        public List<string> fiscal_period_quarterly { get; set; }
    }
    public class BalanceSheetView
    {
        public string id { get; set; }
        public string financialId { get; set; }
        public string definitionSubType { get; set; }
        public string units { get; set; }
        public bool currencyConvertible { get; set; }
        public string templateCategory { get; set; }
        public string templateType { get; set; }
        public string templateSubtype { get; set; }
        public bool bold { get; set; }
        public int position { get; set; }
        public string financialSign { get; set; }
        public string templateId { get; set; }
        public string parent { get; set; }
        public string name { get; set; }
        public int precision { get; set; }
        public string period { get; set; }
        public int divider { get; set; }
    }
}
